# Generated by Django 4.2.7 on 2024-11-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
