# Generated by Django 4.2.7 on 2024-11-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_recipe_ingredient_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Recipe',
            new_name='name',
        ),
    ]
