# Generated by Django 4.2.7 on 2024-12-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_recipe_ingredient_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
