# Generated by Django 4.2.7 on 2024-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_delete_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Ingredients', models.CharField(blank=True, max_length=100, null=True)),
                ('Details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
