# Generated by Django 4.2.7 on 2024-12-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
